"""empty message

Revision ID: 39b9cfe72d93
Revises: e8ee931e49d2
Create Date: 2016-06-17 16:15:59.728895

"""

# revision identifiers, used by Alembic.
revision = '39b9cfe72d93'
down_revision = 'e8ee931e49d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_server_idc_id', table_name='server')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_server_idc_id', 'server', ['idc_id'], unique=False)
    ### end Alembic commands ###
