"""empty message

Revision ID: 10c12fd5b5af
Revises: 3eb9ac3b8fd2
Create Date: 2016-05-29 18:11:38.341008

"""

# revision identifiers, used by Alembic.
revision = '10c12fd5b5af'
down_revision = '3eb9ac3b8fd2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinet', sa.Column('power', sa.String(length=10), nullable=True))
    op.drop_column('cabinet', 'pwer')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinet', sa.Column('pwer', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('cabinet', 'power')
    ### end Alembic commands ###
