"""empty message

Revision ID: 12c3bdc2b4a1
Revises: None
Create Date: 2016-05-29 10:18:12.022223

"""

# revision identifiers, used by Alembic.
revision = '12c3bdc2b4a1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Servertype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('manufacturers_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_index(op.f('ix_Servertype_manufacturers_id'), 'Servertype', ['manufacturers_id'], unique=True)
    op.create_table('cabinet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('idc_id', sa.Integer(), nullable=False),
    sa.Column('power', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('idc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('idc_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('user_interface', sa.String(length=50), nullable=False),
    sa.Column('user_phone', sa.String(length=20), nullable=False),
    sa.Column('rel_cabinet_num', sa.Integer(), nullable=False),
    sa.Column('pact_cabinet_num', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idc_name'), 'idc', ['name'], unique=True)
    op.create_index(op.f('ix_idc_status'), 'idc', ['status'], unique=False)
    op.create_table('manufactures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=20), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('module_letter', sa.String(length=10), nullable=False),
    sa.Column('dev_interface', sa.String(length=100), nullable=False),
    sa.Column('op_interface', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dev_interface'),
    sa.UniqueConstraint('module_letter'),
    sa.UniqueConstraint('op_interface'),
    sa.UniqueConstraint('pid'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('raid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raidtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier')
    op.drop_table('status')
    op.drop_table('raidtype')
    op.drop_table('raid')
    op.drop_table('product')
    op.drop_table('manufactures')
    op.drop_index(op.f('ix_idc_status'), table_name='idc')
    op.drop_index(op.f('ix_idc_name'), table_name='idc')
    op.drop_table('idc')
    op.drop_table('cabinet')
    op.drop_index(op.f('ix_Servertype_manufacturers_id'), table_name='Servertype')
    op.drop_table('Servertype')
    ### end Alembic commands ###
