"""empty message

Revision ID: 1fe77f1378e9
Revises: 4f8d706072a1
Create Date: 2016-05-29 18:09:09.790542

"""

# revision identifiers, used by Alembic.
revision = '1fe77f1378e9'
down_revision = '4f8d706072a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('idc_id', sa.String(length=10), nullable=False),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cabinet_idc_id'), 'cabinet', ['idc_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cabinet_idc_id'), table_name='cabinet')
    op.drop_table('cabinet')
    ### end Alembic commands ###
