"""empty message

Revision ID: 2236c975e81e
Revises: 91ff4ea7669b
Create Date: 2016-05-29 18:07:54.448800

"""

# revision identifiers, used by Alembic.
revision = '2236c975e81e'
down_revision = '91ff4ea7669b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinet', sa.Column('ower', sa.Integer(), nullable=True))
    op.drop_column('cabinet', 'power')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinet', sa.Column('power', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('cabinet', 'ower')
    ### end Alembic commands ###
