"""empty message

Revision ID: 762eeb2d4b30
Revises: 34800a8076da
Create Date: 2016-05-29 17:58:08.290004

"""

# revision identifiers, used by Alembic.
revision = '762eeb2d4b30'
down_revision = '34800a8076da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cabinet', ['power'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cabinet', type_='unique')
    ### end Alembic commands ###
