"""empty message

Revision ID: 91ff4ea7669b
Revises: 762eeb2d4b30
Create Date: 2016-05-29 18:02:31.994352

"""

# revision identifiers, used by Alembic.
revision = '91ff4ea7669b'
down_revision = '762eeb2d4b30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('power', table_name='cabinet')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('power', 'cabinet', ['power'], unique=True)
    ### end Alembic commands ###
