"""empty message

Revision ID: 0c812bd17daf
Revises: 3c8894a49cc8
Create Date: 2016-06-19 11:10:52.837813

"""

# revision identifiers, used by Alembic.
revision = '0c812bd17daf'
down_revision = '3c8894a49cc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zbhost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmdb_hostid', sa.Integer(), nullable=True),
    sa.Column('hostid', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=30), nullable=True),
    sa.Column('ip', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zbhost_cmdb_hostid'), 'zbhost', ['cmdb_hostid'], unique=True)
    op.create_index(op.f('ix_zbhost_hostid'), 'zbhost', ['hostid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zbhost_hostid'), table_name='zbhost')
    op.drop_index(op.f('ix_zbhost_cmdb_hostid'), table_name='zbhost')
    op.drop_table('zbhost')
    ### end Alembic commands ###
