# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "centos6.6"
  
  config.vm.define :default do |default_config|
    default_config.vm.hostname = "elk-01"
    default_config.vm.network :private_network, ip: "192.168.99.20"
    default_config.vm.network :forwarded_port, guest: 9200, host: 9200
    default_config.vm.synced_folder "D:/data", "/share_data"
    default_config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
  end



  config.vm.define :odweb_01 do |odweb_01_config|
    odweb_01_config.vm.hostname = "odweb-01"
    odweb_01_config.vm.network :private_network, ip: "192.168.99.21"
    odweb_01_config.vm.synced_folder "D:/data", "/share_data"
    odweb_01_config.vm.synced_folder "../", "/wwwroot"
    odweb_01_config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end
  
end
