"""empty message

Revision ID: 4ab4fdc15726
Revises: e5155c7bb84a
Create Date: 2016-06-20 17:07:19.971052

"""

# revision identifiers, used by Alembic.
revision = '4ab4fdc15726'
down_revision = 'e5155c7bb84a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('ipinfo', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'ipinfo')
    ### end Alembic commands ###
