"""empty message

Revision ID: 1d24c8791efa
Revises: 39b9cfe72d93
Create Date: 2016-06-18 13:47:09.886325

"""

# revision identifiers, used by Alembic.
revision = '1d24c8791efa'
down_revision = '39b9cfe72d93'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'idc_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('idc_id', mysql.VARCHAR(length=32), nullable=True))
    ### end Alembic commands ###
