"""empty message

Revision ID: 583c80b495b2
Revises: e14211d7b672
Create Date: 2016-06-18 15:22:32.053659

"""

# revision identifiers, used by Alembic.
revision = '583c80b495b2'
down_revision = 'e14211d7b672'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cabinet_idc_id', table_name='cabinet')
    op.drop_column('cabinet', 'idc_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinet', sa.Column('idc_id', mysql.VARCHAR(length=10), nullable=False))
    op.create_index('ix_cabinet_idc_id', 'cabinet', ['idc_id'], unique=False)
    ### end Alembic commands ###
