"""empty message

Revision ID: 41209faa215e
Revises: 583c80b495b2
Create Date: 2016-06-18 15:22:47.061052

"""

# revision identifiers, used by Alembic.
revision = '41209faa215e'
down_revision = '583c80b495b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinet', sa.Column('idc_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cabinet', 'idc_id')
    ### end Alembic commands ###
